/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/casque_01/casque_01.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/casque_01.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.casque_metal.geometry} material={nodes.casque_metal.material} position={[0, 0.202, 0]} />
      <mesh geometry={nodes.casque_other.geometry} material={nodes.casque_other.material} position={[0, 0.202, 0]} />
    </group>
  )
}

useGLTF.preload('/casque_01.glb')
