/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/ceinture_01/ceinture_01.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ceinture_01.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['84746180__111904P'].geometry} material={nodes['84746180__111904P'].material} position={[-0.021, 0.047, -0.027]} rotation={[0, 1.262, 0]} scale={0.01} />
      <mesh geometry={nodes['67364666__2810P'].geometry} material={nodes['67364666__2810P'].material} position={[-0.034, 0.047, 0.025]} rotation={[0, 1.262, -0.217]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/ceinture_01.glb')
